import React, { useState } from "react";

const PKL = () => {
  // const [pokemon, setPokemon] = useState["Pikachu"];
  const [pokemon, setPokemon] = useState("Pikachu");
  const [pokemons, setPokemons] = useState([
    { id: 1, name: "Bulbasur" },
    { id: 2, name: "Ivysaur" },
    { id: 3, name: "Venusaur" },
    { id: 4, name: "Charmander" },
    { id: 5, name: "Charmeleon" },
    { id: 6, name: "Charizard" },
    { id: 7, name: "Squirtle" },
    { id: 8, name: "Wartortle" },
    { id: 9, name: "Blastoise" },
    { id: 10, name: "Caterpie" },
  ]);
  // console.log(pokemons);

  return (
    <>
      <h1>Best Pokemon is : {pokemon}</h1>
      <hr />
      <div className="list1">
        {/* <table>
          <tr>
            <th>Rank No.</th>
            <th>Pokemon Name</th>
          </tr>
          <tr>
            {pokemons.map((item) => {
              {
                // <tr key = {item.id}> - act-dom.development.js:86 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
                 //
              }
              <tbody key={item.id}>
                <td>{item.id}</td>
                {console.log(item)}
                <td>{item.name}</td>
              </tbody>;
            })}
          </tr>
        </table> */}
        <h2>Top 10 - Pokemon List</h2>
        {pokemons.map((item) => [
          <div key={`${item.id} - ${item.name}`}>
            <span>
              {item.id} : {item.name}
            </span>
          </div>,
        ])}
      </div>
    </>
  );
};

export default PKL;
